//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeUtilityProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HOMEUTILITYDATABASEEntities1 : DbContext
    {
        public HOMEUTILITYDATABASEEntities1()
            : base("name=HOMEUTILITYDATABASEEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMIN_TABLE> ADMIN_TABLE { get; set; }
        public virtual DbSet<LOCATION_TABLE> LOCATION_TABLE { get; set; }
        public virtual DbSet<LOGIN_TABLE> LOGIN_TABLE { get; set; }
        public virtual DbSet<ORDER_TABLE> ORDER_TABLE { get; set; }
        public virtual DbSet<PROMO_TABLE> PROMO_TABLE { get; set; }
        public virtual DbSet<SERVICE_TABLE> SERVICE_TABLE { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TECHNICIAN_TABLE> TECHNICIAN_TABLE { get; set; }
        public virtual DbSet<USER_TABLE> USER_TABLE { get; set; }
        public virtual DbSet<USED_EMAIL_TABLE> USED_EMAIL_TABLE { get; set; }
    }
}
