//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeUtilityProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICE_TABLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SERVICE_TABLE()
        {
            this.ORDER_TABLE = new HashSet<ORDER_TABLE>();
            this.TECHNICIAN_TABLE = new HashSet<TECHNICIAN_TABLE>();
        }
    
        public int SERVICE_ID { get; set; }
        public string SERVICE_NAME { get; set; }
        public int SERVICE_COST { get; set; }
        public int DISCOUNT { get; set; }
        public string STATUS { get; set; }
        public int FLAG_1 { get; set; }
        public string FLAG_2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_TABLE> ORDER_TABLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TECHNICIAN_TABLE> TECHNICIAN_TABLE { get; set; }
    }
}
