//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeUtilityProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USED_EMAIL_TABLE
    {
        public int ID { get; set; }
        public string EMAIL { get; set; }
        public string FLAG_1 { get; set; }
        public string FLAG_2 { get; set; }
    }
}
