//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeUtilityProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_TABLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER_TABLE()
        {
            this.ORDER_TABLE = new HashSet<ORDER_TABLE>();
        }
    
        public int USER_ID { get; set; }
        public string NAME { get; set; }
        public string EMAIL { get; set; }
        public string PASSWORD { get; set; }
        public int PHONE { get; set; }
        public int LOCATION_ID { get; set; }
        public string ADDRESS { get; set; }
        public string RATINGS { get; set; }
        public string STATUS { get; set; }
        public int FLAG_1 { get; set; }
        public string FLAG_2 { get; set; }
    
        public virtual LOCATION_TABLE LOCATION_TABLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_TABLE> ORDER_TABLE { get; set; }
    }
}
